# Generated by Django 5.0.6 on 2025-03-12 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_doctoradd_doctor_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoradd',
            name='Date_joined',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 9, 23, 51, 803329)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctoradd',
            name='Doctor_spacial',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('General', 'General'), ('Orthopedic', 'Orthopedic'), ('Psychiatrist', 'Psychiatrist'), ('Oncologist', 'Oncologist'), ('Gynecologist', 'Gynecologist'), ('Urologist', 'Urologist')], max_length=200),
        ),
    ]
